name = "thegoodplace-openai-api"
main = "src/index.ts"
compatibility_date = "2024-07-22"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "thegoodplace-db"
database_id = "ef4ccc54-d9ba-44e3-a7da-9e68197e2614"